### ISSUE TITLE
TypeError: Cannot read property 'JWT' of undefined

### ISSUE THREAD

**Issue by Ether0x** [firebase/quickstart-nodejs#19]
Line 25: TypeError: Cannot read property 'JWT' of undefined

Looking at the `google` object, this path to JWT does not exist. Instead it requires:

`jwtClient = new google.google.auth.JWT`

**Comment by samtstern** [comment]
@Ether0x nice catch!  I noticed that the pattern shown by the `googleapis` docs is:

```js
var {google} = require('googleapis');

// ...

google.auth.JWT
```

So I went with that.

**Comment by rbar2** [comment]
I am getting this same error but have tried **both ways above and** the one outlined here: https://firebase.google.com/docs/database/rest/auth.  

I had been doing it this way with no trouble but redeployed (without changing anything) this function for the first time in a bit later and now this is crashing with the error above:

var google = require("googleapis");

// Load the service account key JSON file.
var serviceAccount = require("path/to/serviceAccountKey.json");

// Define the required scopes.
var scopes = [
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/firebase.database"
];

// Authenticate a JWT client with the service account.
var jwtClient = new google.auth.JWT(
  serviceAccount.client_email,
  null,
  serviceAccount.private_key,
  scopes
);

Any ideas what could be causing this issue? 🙏

**Comment by stevanpopo** [comment]
@samtstern I think you are actually right. There is a good thread [here](https://github.com/google/google-api-nodejs-client/issues/1053).

From Justin's comment:

1. Make sure you didn't npm install google-auth-library. If you did, delete it from your package.json, and run npm install again.

2. Import the library using const {google} = require('googleapis');, notice the {} around google.

3. In your callback, instead of looking for response.items, use response.data.items. This will be required in any of the callbacks coming from the API.

**Comment by sw-ms-milapthakkar** [comment]
@rbar2 you needs to be add var {google} = require("googleapis"); instead of var google = require("googleapis");

**Comment by ThomasGHenry** [comment]
google's docs should reflect their intended usage
https://firebase.google.com/docs/reference/dynamic-links/analytics#api_authorization

**Comment by samtstern** [comment]
@ThomasGHenry thanks for catching that, I will get it updated.
