### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

### ISSUE THREAD

**Issue by nic** [firebase/quickstart-nodejs#9]
var firebase = require("firebase")
firebase.initializeApp(...)
var db = firebase.database()

This simple three lines throw the Deprecation Warning:
Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

node --version
v7.0.0

**Comment by nicolasgarnier** [comment]
@jwngr ptal

**Comment by jwngr** [comment]
Thanks for reporting this @nic! I don't think we were aware of this deprecation warning. It should be safe to ignore for now and we will make sure to update our usage of `Buffer` in an upcoming release so that Firebase works in future versions of Node.js. I'm going to close this issue since we are now tracking this internally and this isn't the best spot to track this bug.
